lvfs/shards/routes.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright 2019 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

from collections import defaultdict
from typing import Dict, List, Any
from io import StringIO
import json
import csv

from uuid import UUID

from flask import (
    Blueprint,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
    g,
)
from flask_login import login_required
from sqlalchemy.exc import NoResultFound, IntegrityError

from lvfs import db, cache

from lvfs.components.models import (
    Component,
    ComponentShard,
    ComponentShardClaim,
    ComponentShardInfo,
)
from lvfs.claims.models import Claim
from lvfs.util import admin_login_required, _validate_guid


bp_shards = Blueprint("shards", __name__, template_folder="templates")


@bp_shards.route("/")
@login_required
def route_list() -> Any:
    # security check
    if not g.user.check_acl("@partner"):
        return redirect(url_for("main.route_dashboard"), 302)

    # only show shards with the correct group_id
    shards = (
        db.session.query(ComponentShardInfo)
        .order_by(ComponentShardInfo.cnt.desc())
        .all()
    )
    return render_template("shard-list.html", category="firmware", shards=shards)


@bp_shards.post("/create")
@login_required
def route_create() -> Any:
    # security check
    if not g.user.check_acl("@partner"):
        return redirect(url_for("main.route_dashboard"), 302)

    # ensure has enough data
    if "guid" not in request.form:
        flash("No form data found", "warning")
        return redirect(url_for("shards.route_list"))
    guid = request.form["guid"].lower()
    try:
        _ = UUID(guid)
    except ValueError:
        flash("Failed to add shard: Not a GUID", "warning")
        return redirect(url_for("shards.route_list"))

    # add ComponentShardInfo
    try:
        info = ComponentShardInfo(guid=guid)
        db.session.add(info)
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Failed to add shard: Already exists", "info")
        return redirect(url_for("shards.route_list"))
    flash("Added shard", "info")
    return redirect(
        url_for(
            "shards.route_show", component_shard_info_id=info.component_shard_info_id
        )
    )


@bp_shards.post("/<int:component_shard_info_id>/modify")
@login_required
def route_modify(component_shard_info_id: int) -> Any:
    # security check
    if not g.user.check_acl("@partner"):
        return redirect(url_for("main.route_dashboard"), 302)

    # find shard
    try:
        shard = (
            db.session.query(ComponentShardInfo)
            .filter(
                ComponentShardInfo.component_shard_info_id == component_shard_info_id
            )
            .with_for_update(of=ComponentShardInfo)
            .one()
        )
    except NoResultFound:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # modify shard
    keys: List[str] = []
    if g.user.check_acl("@partner"):
        keys.append("name")
        keys.append("description")
    if g.user.check_acl("@admin"):
        keys.append("claim_id")
    for key in keys:
        if key in request.form:
            setattr(shard, key, request.form[key] or None)
    db.session.commit()

    # success
    flash("Modified shard", "info")
    return route_show(component_shard_info_id)


@bp_shards.post("/<int:component_shard_info_id>/delete")
@login_required
def route_delete(component_shard_info_id: int) -> Any:
    # security check
    if not g.user.check_acl("@partner"):
        return redirect(url_for("main.route_dashboard"), 302)

    try:
        db.session.query(ComponentShardInfo).filter(
            ComponentShardInfo.component_shard_info_id == component_shard_info_id
        ).delete()
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Cannot delete", "danger")
        return redirect(url_for("shards.route_list"))
    flash("Deleted shard", "info")
    return redirect(url_for("shards.route_list"))


@bp_shards.route("/<int:component_shard_info_id>/details")
@login_required
def route_show(component_shard_info_id: int) -> Any:
    # security check
    if not g.user.check_acl("@partner"):
        return redirect(url_for("main.route_dashboard"), 302)

    # find shard
    try:
        shard = (
            db.session.query(ComponentShardInfo)
            .filter(
                ComponentShardInfo.component_shard_info_id == component_shard_info_id
            )
            .one()
        )
    except NoResultFound:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # show details
    claims = db.session.query(Claim).order_by(Claim.summary).all()
    return render_template(
        "shard-details.html", category="firmware", claims=claims, shard=shard
    )


@bp_shards.route("/<int:component_shard_info_id>/components")
@login_required
def route_components(component_shard_info_id: int) -> Any:
    # find shard
    try:
        shard_info = (
            db.session.query(ComponentShardInfo)
            .filter(
                ComponentShardInfo.component_shard_info_id == component_shard_info_id
            )
            .one()
        )
    except NoResultFound:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # get shards with a unique component appstream ID
    shards = (
        db.session.query(ComponentShard)
        .join(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .join(Component)
        .distinct(Component.appstream_id)
        .order_by(Component.appstream_id, ComponentShard.name.desc())
        .all()
    )
    unique_mds: Dict[str, List[Component]] = defaultdict(list)
    for shard in shards:
        if shard.md not in unique_mds[shard.name]:
            if not shard.md.fw.check_acl("@view"):
                continue
            unique_mds[shard.name].append(shard.md)

    # show details
    return render_template(
        "shard-components.html",
        category="firmware",
        unique_mds=unique_mds,
        shard=shard_info,
    )


@bp_shards.route("/<int:component_shard_info_id>/checksums")
@login_required
@admin_login_required
def route_checksums(component_shard_info_id: int) -> Any:
    # find shard
    try:
        shard_info = (
            db.session.query(ComponentShardInfo)
            .filter(
                ComponentShardInfo.component_shard_info_id == component_shard_info_id
            )
            .one()
        )
    except NoResultFound:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # get shards with a unique component appstream ID
    shards_by_checksum: Dict[str, List[ComponentShard]] = defaultdict(list)
    for shard in (
        db.session.query(ComponentShard)
        .join(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
    ):
        shards_by_checksum[shard.checksum].append(shard)

    # show details
    return render_template(
        "shard-checksums.html",
        category="firmware",
        shards_by_checksum=shards_by_checksum,
        shard=shard_info,
    )


@bp_shards.route("/<int:component_shard_info_id>/claims")
@login_required
@admin_login_required
def route_claims(component_shard_info_id: int) -> Any:
    # find shard
    try:
        shard = (
            db.session.query(ComponentShardInfo)
            .filter(
                ComponentShardInfo.component_shard_info_id == component_shard_info_id
            )
            .one()
        )
    except NoResultFound:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # get claims for this ComponentShardInfo
    claims = (
        db.session.query(ComponentShardClaim)
        .filter(ComponentShardClaim.component_shard_info_id == component_shard_info_id)
        .all()
    )

    # show details
    claims_all = db.session.query(Claim).order_by(Claim.summary).all()
    return render_template(
        "shard-claims.html",
        category="firmware",
        claims=claims,
        claims_all=claims_all,
        shard=shard,
    )


@bp_shards.route(
    "/<int:component_shard_info_id>/claim/<int:component_shard_claim_id>/delete",
    methods=["POST"],
)
@login_required
@admin_login_required
def route_shard_claim_delete(
    component_shard_info_id: int, component_shard_claim_id: int
) -> Any:
    # find shard
    try:
        db.session.query(ComponentShardClaim).filter(
            ComponentShardClaim.component_shard_info_id == component_shard_info_id
        ).filter(
            ComponentShardClaim.component_shard_claim_id == component_shard_claim_id
        ).delete()
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Cannot delete", "danger")
        return redirect(url_for("shards.route_list"))
    flash("Deleted shard claim", "info")
    return redirect(
        url_for("shards.route_claims", component_shard_info_id=component_shard_info_id)
    )


@bp_shards.post("/<int:component_shard_info_id>/claim/create")
@login_required
@admin_login_required
def route_shard_claim_create(component_shard_info_id: int) -> Any:
    # ensure has enough data
    for key in ["checksum", "claim_id"]:
        if key not in request.form:
            flash(f"No {key} form data found!", "warning")
            return redirect(url_for("shards.route_list"))

    # add issue
    try:
        claim = ComponentShardClaim(
            component_shard_info_id=component_shard_info_id,
            checksum=request.form["checksum"],
            claim_id=request.form["claim_id"],
        )
        db.session.add(claim)
        db.session.commit()
    except IntegrityError:

lvfs/shards/templates/shard-checksums.html
{% extends "default.html" %}
{% block title %}Component Shard Checksums{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}

{% for checksum in shards_by_checksum %}
{% set shards = shards_by_checksum[checksum] %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title"><code>{{checksum}}</code></h2>
    <ul class="list-group">
{% for shard in shards|sort(attribute='name_with_vendor') %}
{% set md = shard.md %}
{% set remote = md.fw.remote %}
      <li class="list-group-item">
        <a href="{{url_for('components.route_show', component_id=md.component_id)}}">
          {{md.name_with_vendor}} &mdash; {{md.version_display}}
          <img class="fa float-right" src="{{url_for('cdn', filename='img/' + remote.icon_name + '-solid.svg')}}" width="16"
            alt="{{remote.name}}"
            title="{{remote.description}}"/>
        </a>
      </li>
{% endfor %}
    </ul>
    <a class="card-link btn btn-info mt-3"
       href="{{url_for('shards.route_download', component_shard_id=shards[0].component_shard_id)}}">
      Download File
{% if shard.size %}
      ({{format_size(shard.size)}})
{% endif %}
    </a>
  </div>
</div>
{% endfor %}

{% endblock %}

lvfs/shards/templates/shard-claims.html
{% extends "default.html" %}
{% block title %}Component Shard Claims{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}

<div class="card">
  <div class="card-body">
    <h2 class="card-title">Component Shard Claims</h2>
<table class="table">
  <tr class="row">
    <th class="col col-sm-6">Checksum</th>
    <th class="col col-sm-4">Claim</th>
    <th class="col col-sm-2">&nbsp;</th>
  </tr>
{% if claims|length == 0 %}
  <tr class="row">
    <td class="col col-sm-12"><p class="text-muted">No claims exist yet.</p></td>
  </tr>
</p>
{% else %}
{% for claim in claims|sort(attribute='checksum') %}
  <tr class="row">
    <td class="col col-sm-6"><code>{{claim.checksum|truncate(64, False, '…')}}</code></td>
    <td class="col col-sm-4"><code>{{claim.claim.summary}}</code></td>
    <td class="col col-sm-2">
      <form action="{{url_for('shards.route_shard_claim_delete',
                              component_shard_info_id=claim.component_shard_info_id,
                              component_shard_claim_id=claim.component_shard_claim_id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
        <button class="btn-block btn btn-danger">Delete</button>
      </form>
    </td>
  </tr>
{% endfor %}
{% endif %}
  <tr class="row">
    <form method="post" action="{{url_for('shards.route_shard_claim_create',
                                          component_shard_info_id=shard.component_shard_info_id)}}">
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
    <td class="col col-sm-6">
      <input type="text" class="form-control" name="checksum" value="" placeholder="Checksum..." required>
    </td>
    <td class="col col-sm-4">
    <select class="form-control" name="claim_id">
{% for claim in claims_all %}
      <option value="{{claim.claim_id}}">{{claim.summary}}</option>
{% endfor %}
    </select>
    </td>
    <td class="col col-sm-2">
      <input type="submit" class="btn btn-block btn-primary" value="Add">
    </td>
    </form>
  </tr>
</table>
  </div>
</div>

{% endblock %}

lvfs/shards/templates/shard-components.html
{% extends "default.html" %}
{% block title %}Component Shard Components{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}

{% for appstream_id in unique_mds %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title"><code>{{appstream_id}}</code></h2>
    <ul class="list-group">
{% for md in unique_mds[appstream_id]|sort(attribute='name_with_vendor') %}
      <li class="list-group-item">{{md.name_with_vendor}}</li>
{% endfor %}
    </ul>
  </div>
</div>
{% endfor %}

{% endblock %}

lvfs/shards/templates/shard-details.html
{% extends "default.html" %}
{% block title %}Component Shard Details{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Component Shard Details</h2>
<form method="post" action="{{url_for('shards.route_modify', component_shard_info_id=shard.component_shard_info_id)}}">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <div class="form-group card-text">
    <label for="name">Name</label>
    <input class="form-control" type="text" id="name" name="name" placeholder="NvmeRecovery" value="{{shard.name or ''}}"/>
  </div>
  <div class="form-group">
    <label for="description">Description:</label>
    <textarea class="form-control" id="description" name="description" rows="10">{{shard.description if shard.description}}</textarea>
  </div>
{% if g.user.check_acl('@admin') %}
  <div class="form-group">
    <label for="claim_id">GUID Claim:</label>
    <select class="form-control" id="claim_id" name="claim_id">
      <option value="" {{ 'selected' if shard.claim_id == 0 }}>None</option>
{% for claim in claims %}
      <option value="{{claim.claim_id}}" {{ 'selected' if shard.claim_id == claim.claim_id }}>{{claim.summary}}</option>
{% endfor %}
    </select>
  </div>
{% endif %}
  <input type="submit" class="card-link btn btn-primary" value="Save">
  <button type="button" class="card-link btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
</form>
  </div>
</div>

<!-- modal dialog -->
<div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Really Delete Shard?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Once deleted, shard info can not be recovered.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{url_for('shards.route_delete', component_shard_info_id=shard.component_shard_info_id)}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
          <button class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

lvfs/shards/templates/shard-list.html
{% extends "default.html" %}
{% block title %}Component GUIDs{% endblock %}

{% block content %}

<form id="import-csv" method="post" action="{{url_for('shards.route_import_csv')}}" enctype="multipart/form-data" class="form">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
</form>

<div class="card form">
  <div class="card-body">
    <h4 class="card-title">Component GUIDs</h4>
    <p class="card-text">
      Information about what GUIDs maps to each firmware is collected from uploaded firmware and
      also added manually by firmware professionals.
      This data must be contributed and distributed under the
      <a href="https://creativecommons.org/share-your-work/public-domain/cc0/">CC0-1.0</a> license.
    </p>
{% if g.user.check_acl('@admin') %}
    <input form="import-csv" type="file" class="form-control-file mb-3" id="file-input" id="file" name="file" required/>
    <input form="import-csv" type="submit" class="card-link btn btn-warning" value="Import From CSV">
{% endif %}
    <a class="card-link btn btn-primary" href="{{url_for('shards.route_export_csv')}}">Export As CSV</a>
    <a class="card-link btn btn-primary" href="{{url_for('shards.route_export_json')}}">Export As JSON</a>
  </div>
</div>

{% if shards|length == 0 %}
<div class="card">
  <div class="card-body">
    <p class="card-text text-secondary">
      No component GUIDs have been created.
    </p>
  </div>
</div>

{% else %}

{% for shard in shards %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">
      <code>{{shard.name or 'Invalid'}}</code> ({{shard.cnt}})
      <code class="float-right">{{shard.guid}}</code>
    </h2>
    <div class="card-text mb-3">
{% if shard.description %}
      {{shard.description}}
{% else %}
      No description!
{% endif %}
    </div>
    <a class="card-link btn btn-info"
      href="{{url_for('shards.route_show', component_shard_info_id=shard.component_shard_info_id)}}"
      role="button">Details</a>
    <a class="card-link btn btn-info"
      href="{{url_for('firmware.route_shard_search', kind='guid', value=shard.guid)}}"
      role="button">Firmware</a>
  </div>
</div>
{% endfor %}

{% endif %}

<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">Create a new shard</h2>
    <form method="post" action="{{url_for('shards.route_create')}}" class="form">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <div class="form-group card-text">
        <label for="guid">GUID</label>
        <input class="form-control" type="text" id="guid" name="guid" placeholder="9b3ada4f-ae56-4c24-8dea-f03b7558ae50" required />
      </div>
      <input class="card-link btn btn-primary" type="submit" value="Add"/>
    </form>
  </div>
</div>

{% endblock %}

lvfs/shards/templates/shard-nav.html
<nav class="row">
  <div class="col col-sm-1 btn-group mb-3">
    <a class="btn btn-falcon-default mr-sm-3"
      href="{{url_for('shards.route_list')}}">
      <img class="fa" src="{{url_for('cdn', filename='img/arrow-left-solid.svg')}}" width="16px" height="16px" />
    </a>
  </div>
  <div class="col col-sm-10 text-center mb-3">
    <div class="btn-group" role="group">
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_show' else 'default'}}"
        href="{{url_for('shards.route_show', component_shard_info_id=shard.component_shard_info_id)}}">Details</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_components' else 'default'}}"
        href="{{url_for('shards.route_components', component_shard_info_id=shard.component_shard_info_id)}}">Components</a>
{% if g.user.check_acl('@admin') %}
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_checksums' else 'default'}}"
        href="{{url_for('shards.route_checksums', component_shard_info_id=shard.component_shard_info_id)}}">Variants</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_claims' else 'default'}}"
        href="{{url_for('shards.route_claims', component_shard_info_id=shard.component_shard_info_id)}}">Checksum Claims</a>
{% endif %}
    </div>
  </div>
</nav>