lvfs/tasks/routes.py
#!/usr/bin/python3
#
# Copyright 2022 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

import datetime
from typing import Any, Optional

from flask import Blueprint, request, url_for, redirect, flash, render_template, g
from flask_login import login_required
from sqlalchemy.exc import NoResultFound, IntegrityError

from lvfs import db

from lvfs.util import admin_login_required
from lvfs.tasks.models import Task, TaskScheduler

bp_tasks = Blueprint("tasks", __name__, template_folder="templates")


@bp_tasks.route("/")
@bp_tasks.route("/state/<state>")
@bp_tasks.route("/limit/<int:limit>")
@login_required
@admin_login_required
def route_list(state: Optional[str] = None, limit: int = 15) -> Any:
    page = request.args.get("page", 1, type=int)
    stmt = db.session.query(Task)
    if state == "pending":
        stmt = stmt.filter(Task.started_ts == None, Task.ended_ts == None)
    elif state == "running":
        stmt = stmt.filter(Task.started_ts != None, Task.ended_ts == None)
    task_pgs = stmt.order_by(Task.task_id.desc()).paginate(page=page, per_page=limit)
    return render_template(
        "task-list.html", category="admin", task_pgs=task_pgs, state=state
    )


@bp_tasks.post("/delete/<int:task_id>")
@login_required
@admin_login_required
def route_delete(task_id: int) -> Any:
    # get tests
    try:
        db.session.query(Task).filter(Task.task_id == task_id).delete()
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Task cannot be deleted", "warning")
        return redirect(url_for("tasks.route_list"))

    flash("Task has been deleted", "info")
    return redirect(url_for("tasks.route_list"))


@bp_tasks.post("/<int:task_id>/cancel")
@login_required
@admin_login_required
def route_cancel(task_id: int) -> Any:
    # get tests
    try:
        task = (
            db.session.query(Task)
            .filter(Task.task_id == task_id)
            .with_for_update(of=Task)
            .one()
        )
    except NoResultFound:
        flash("No task matched", "warning")
        return redirect(url_for("tasks.route_list"))
    try:
        task.ended_ts = datetime.datetime.utcnow()
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Task cannot be canceled")
        return redirect(url_for("tasks.route_list"))

    flash("Task has been canceled", "info")
    return redirect(url_for("tasks.route_list"))


@bp_tasks.post("/<int:task_id>/retry")
@login_required
@admin_login_required
def route_retry(task_id: int) -> Any:
    try:
        task = (
            db.session.query(Task)
            .filter(Task.task_id == task_id)
            .with_for_update(of=Task)
            .one()
        )
    except NoResultFound:
        flash("No task matched", "warning")
        return redirect(url_for("tasks.route_list"))
    db.session.add(
        Task(
            caller=task.caller,
            user=task.user,
            priority=task.priority,
            value=task.value,
            url=task.url,
            function=task.function,
            force=True,
        )
    )
    db.session.commit()

    flash("Task has been rescheduled", "info")
    return redirect(url_for("tasks.route_list"))


@bp_tasks.route("/scheduler/all")
@login_required
@admin_login_required
def route_scheduler_list() -> Any:
    task_scheds = (
        db.session.query(TaskScheduler)
        .order_by(TaskScheduler.task_scheduler_id.asc())
        .all()
    )
    return render_template(
        "task-scheduler-list.html", category="admin", task_scheds=task_scheds
    )


@bp_tasks.post("/scheduler/create")
@login_required
@admin_login_required
def route_scheduler_create() -> Any:
    # add scheduled task
    try:
        task_sched = TaskScheduler(
            function=request.form["function"], user=g.user, interval=0
        )
        db.session.add(task_sched)
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Already exists", "warning")
        return redirect(url_for("tasks.route_scheduler_list"))
    except KeyError:
        flash("No form data found!", "warning")
        return redirect(url_for("tasks.route_scheduler_list"))
    flash("Added task scheduler", "info")
    return redirect(
        url_for(
            "tasks.route_scheduler_show", task_scheduler_id=task_sched.task_scheduler_id
        )
    )


@bp_tasks.post("/scheduler/<int:task_scheduler_id>/delete")
@login_required
@admin_login_required
def route_scheduler_delete(task_scheduler_id: int) -> Any:
    # get task
    try:
        db.session.query(TaskScheduler).filter(
            TaskScheduler.task_scheduler_id == task_scheduler_id
        ).delete()
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Cannot delete", "danger")
        return redirect(url_for("tasks.route_scheduler_list"))
    flash("Deleted task scheduler", "info")
    return redirect(url_for("tasks.route_scheduler_list"))


@bp_tasks.post("/scheduler/<int:task_scheduler_id>/modify")
@login_required
@admin_login_required
def route_scheduler_modify(task_scheduler_id: int) -> Any:
    # find task
    try:
        task_sched = (
            db.session.query(TaskScheduler)
            .filter(TaskScheduler.task_scheduler_id == task_scheduler_id)
            .with_for_update(of=TaskScheduler)
            .one()
        )
    except NoResultFound:
        flash("No task scheduler found", "info")
        return redirect(url_for("tasks.route_scheduler_list"))

    # modify task
    for key in ["interval", "function", "priority"]:
        if key in request.form:
            setattr(task_sched, key, request.form[key])
    db.session.commit()

    # success
    flash("Modified task scheduler", "info")
    return redirect(
        url_for("tasks.route_scheduler_show", task_scheduler_id=task_scheduler_id)
    )


@bp_tasks.route("/scheduler/<int:task_scheduler_id>")
@login_required
@admin_login_required
def route_scheduler_show(task_scheduler_id: int) -> Any:
    # find task
    try:
        task_sched = (
            db.session.query(TaskScheduler)
            .filter(TaskScheduler.task_scheduler_id == task_scheduler_id)
            .one()
        )
    except NoResultFound:
        flash("No task scheduler found", "info")
        return redirect(url_for("tasks.route_scheduler_list"))

    # show details
    return render_template("task-details.html", category="admin", task_sched=task_sched)

lvfs/tasks/templates/task-details.html
{% extends "default.html" %}
{% block title %}Task Scheduler Details{% endblock %}
{% block nav %}{% include 'task-nav.html' %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Task Scheduler Details</h2>
<form method="post" action="{{url_for('tasks.route_scheduler_modify', task_scheduler_id=task_sched.task_scheduler_id)}}">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <div class="form-group">
    <label for="value">Function:</label>
    <input type="text" class="form-control" id="function" name="function" value="{{task_sched.function}}" required />
  </div>
  <div class="form-group">
    <label for="value">Interval:</label>
    <input type="number" class="form-control" id="interval" name="interval" value="{{task_sched.interval}}" required />
  </div>
  <div class="form-group">
    <label for="value">Priority:</label>
    <input type="number" class="form-control" id="priority" name="priority" value="{{task_sched.priority}}" required />
  </div>
  <input type="submit" class="card-link btn btn-primary" value="Save">
  <button type="button" class="card-link btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
</form>
  </div>
</div>

<!-- modal dialog -->
<div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Really Delete Task Scheduler?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        The LVFS might break if you remove a task scheduler.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{url_for('tasks.route_scheduler_delete', task_scheduler_id=task_sched.task_scheduler_id)}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
          <button class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

lvfs/tasks/templates/task-list.html
{% extends "default.html" %}
{% block title %}Tasks {{task_pgs.page}} of {{task_pgs.pages}}{% endblock %}
{% block nav %}{% include 'task-nav.html' %}{% endblock %}

{% block content %}

{% if not task_pgs %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Tasks</h2>
    <p class="card-text">
      No tasks have been created.
    </p>
  </div>
</div>

{% else %}

{% for task in task_pgs.items %}
<div class="card mt-3">
  <h2 class="card-header card-title list-group-item-{{task.color}}">
    <code>#{{task.task_id}} {{task.function}}</code>
    <span class="float-right"><code>{{task.caller}}</code></span>
  </h2>
  <div class="card-body">
    <table class="table">
      <tr class="row table-borderless">
        <th class="col-3">Creating User</th>
        <td class="col-9"><code>{{task.user.username}}</code></td>
      </tr>
{% if task.value %}
      <tr class="row">
        <th class="col-3">Value</th>
        <td class="col-9"><code>{{task.value}}</code></td>
      </tr>
{% endif %}
      <tr class="row">
        <th class="col-3">Priority</th>
        <td class="col-9">{{task.priority_description}}</td>
      </tr>
      <tr class="row">
        <th class="col-3">Created</th>
        <td class="col-9">{{task.created_ts.strftime('%F %T')}}</td>
      </tr>
{% if task.started_ts %}
      <tr class="row">
        <th class="col-3">Started</th>
        <td class="col-9">{{task.started_ts.strftime('%F %T')}}</td>
      </tr>
{% endif %}
{% if task.started_ts and task.ended_ts %}
      <tr class="row">
        <th class="col-3">Duration</th>
        <td class="col-9">{{format_humanize_naturaldelta(task.ended_ts - task.started_ts)}}</td>
      </tr>
{% endif %}
{% if task.container_id %}
      <tr class="row">
        <th class="col-3">Container</th>
        <td class="col-9"><code>{{task.container_id}}</code></td>
      </tr>
{% endif %}
{% if task.status %}
      <tr class="row">
        <th class="col-3">Status</th>
        <td class="col-9">
          {{task.status}}…
{% if task.percentage %}
          {{task.percentage}}%
{% endif %}
        </td>
      </tr>
{% elif task.is_running %}
      <tr class="row">
        <th class="col-3">Status</th>
        <td class="col-9">Processing…</td>
      </tr>
{% endif %}
    </table>
{% if task.attributes %}
    <ul class="card-text">
{% for attr in task.attributes %}
      <li class="list-group-item">
{% if task.started_ts and attr.created_ts %}
        <span class="float-right">| {{format_humanize_naturaldelta(attr.created_ts - task.started_ts)}}</span>
{% endif %}
{% if attr.message %}
        <code>{{attr.title}}: {{attr.message}}</code>
{% else %}
        <code>{{attr.title}}</code>
{% endif %}
      </li>
{% endfor %}
    </ul>
{% endif %}
{% if task.is_running %}
    <form action="{{url_for('tasks.route_cancel', task_id=task.task_id)}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <button class="card-link btn btn-warning float-right mx-1">Cancel</button>
    </form>
{% else %}
    <form action="{{url_for('tasks.route_delete', task_id=task.task_id)}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <button class="card-link btn btn-danger float-right mx-1">Delete</button>
    </form>
    <form action="{{url_for('tasks.route_retry', task_id=task.task_id)}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <button class="card-link btn btn-warning float-right mx-1">Retry</button>
    </form>
{% endif %}
{% if task.url %}
    <a class="card-link btn btn-info float-right mx-1" href="{{task.url}}" role="button">Details &raquo;</a>
{% endif %}
  </div>
</div>
{% endfor %}

<!-- pagination -->
<nav aria-label="Page navigation">
  <ul class="pagination pagination-lg mt-3">
    <li class="page-item {% if task_pgs.page == 1 %}disabled{% endif %}">
      <a class="page-link" href="{{url_for('tasks.route_list', page=task_pgs.prev_num)}}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
        <span class="sr-only">Previous</span>
      </a>
    </li>
{% for page_num in task_pgs.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
{% if page_num %}
    <li class="page-item {% if task_pgs.page == page_num %}active{% endif %}">
      <a class="page-link" href="{{url_for('tasks.route_list', page=page_num)}}">{{page_num}}</a>
    </li>
{% else %}
    <li class="page-item disabled"><a class="page-link">...</a></li>
{% endif %}
{% endfor %}
    <li class="page-item {% if task_pgs.page == task_pgs.pages %}disabled{% endif %}">
      <a class="page-link" href="{{url_for('tasks.route_list', page=task_pgs.next_num)}}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
        <span class="sr-only">Next</span>
      </a>
    </li>
  </ul>
</nav>

{% endif %}

{% endblock %}

lvfs/tasks/templates/task-nav.html
<nav>
  <div class="text-center mb-3">
    <div class="btn-group" role="group">
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'tasks.route_list' and not state else 'default'}}"
        href="{{url_for('tasks.route_list')}}">Recent</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'tasks.route_list' and state == 'pending' else 'default'}}"
        href="{{url_for('tasks.route_list', state='pending')}}">Pending</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'tasks.route_list' and state == 'running' else 'default'}}"
        href="{{url_for('tasks.route_list', state='running')}}">Running</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'tasks.route_scheduler_list' else 'default'}}"
        href="{{url_for('tasks.route_scheduler_list')}}">Schedulers</a>
    </div>
  </div>
</nav>

lvfs/tasks/templates/task-scheduler-list.html
{% extends "default.html" %}
{% block title %}Task Schedulers{% endblock %}
{% block nav %}{% include 'task-nav.html' %}{% endblock %}

{% block content %}

{% if task_scheds|length == 0 %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Tasks</h2>
    <p class="card-text">
      No tasks schedulers have been created.
    </p>
  </div>
</div>

{% else %}

{% for task_sched in task_scheds %}
{% set task = task_sched.task %}

{% if task %}
<form id="retry_{{task.task_id}}" action="{{url_for('tasks.route_retry', task_id=task.task_id)}}" method="POST">
  <input form="retry_{{task.task_id}}" type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
</form>
{% endif %}

<div class="card mt-3">
  <h2 class="card-header card-title list-group-item-{{task_sched.color}}">
      <code>{{task_sched.function}}</code>
{% if task_sched.interval %}
    <span class="float-right">every {{task_sched.interval}}h</span>
{% endif %}
  </h2>
  <div class="card-body">
{% if task %}
    <table class="table">
      <tr class="row table-borderless">
        <th class="col-3">Creating User</th>
        <td class="col-9"><code>{{task.user.username}}</code></td>
      </tr>
      <tr class="row">
        <th class="col-3">Priority</th>
        <td class="col-9">{{task.priority_description}}</td>
      </tr>
{% if task.value %}
      <tr class="row">
        <th class="col-3">Value</th>
        <td class="col-9"><code>{{task.value}}</code></td>
      </tr>
{% endif %}
{% if task.started_ts %}
      <tr class="row">
        <th class="col-3">Started</th>
        <td class="col-9">{{task.started_ts.strftime('%F %T')}}</td>
      </tr>
{% endif %}
{% if task.ended_ts %}
      <tr class="row">
        <th class="col-3">Duration</th>
        <td class="col-9">{{format_humanize_naturaldelta(task.ended_ts - task.started_ts)}}</td>
      </tr>
{% endif %}
    </table>
{% if task.attributes %}
    <ul class="card-text">
{% for attr in task.attributes %}
      <li class="list-group-item">
{% if attr.message %}
        <code>{{attr.title}}: {{attr.message}}</code>
{% else %}
        <code>{{attr.title}}</code>
{% endif %}
      </li>
{% endfor %}
    </ul>
{% endif %}
{% endif %}
    <a class="card-link btn btn-info"
      href="{{url_for('tasks.route_scheduler_show', task_scheduler_id=task_sched.task_scheduler_id)}}"
      role="button">Details &raquo;</a>
{% if task and task.ended_ts %}
    <button form="retry_{{task.task_id}}" class="card-link btn btn-warning float-right">Retry</button>
{% endif %}
  </div>
</div>
{% endfor %}


{% endif %}

<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">Create a new task scheduler</h2>
    <form method="post" action="{{url_for('tasks.route_scheduler_create')}}" class="form">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <div class="form-group card-text">
        <label for="value">Function name:</label>
        <input class="form-control" type="text" id="function" name="function" placeholder="lvfs.main.utils.task_regenerate" required />
      </div>
      <input class="card-link btn btn-primary" type="submit" value="Add"/>
    </form>
  </div>
</div>

{% endblock %}