lvfs/licenses/models.py
#!/usr/bin/python3
#
# Copyright 2020 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later
#
# pylint: disable=too-few-public-methods

import datetime

from sqlalchemy import (
    Column,
    Integer,
    Text,
    Boolean,
    DateTime,
    ForeignKey,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from lvfs import db


class LicenseAlias(db.Model):  # type: ignore
    __tablename__ = "license_alias"

    license_alias_id = Column(Integer, primary_key=True)
    license_id = Column(
        Integer, ForeignKey("licenses.license_id"), nullable=False, index=True
    )
    value = Column(Text, nullable=False, unique=True)  # 'CC0-1.0'
    ctime = Column(DateTime, nullable=False, default=datetime.datetime.utcnow)
    user_id = Column(Integer, ForeignKey("users.user_id"), nullable=False)

    lic = relationship("License")
    user = relationship("User", foreign_keys=[user_id])

    __table_args__ = (
        UniqueConstraint(
            "license_id",
            "value",
            name="uq_component_alias_license_id_value",
        ),
    )

    def __repr__(self) -> str:
        return f"LicenseAlias({self.license_alias_id},{self.license_id})"


class License(db.Model):  # type: ignore
    __tablename__ = "licenses"

    license_id = Column(Integer, primary_key=True)
    value = Column(Text, nullable=False, unique=True)  # 'CC0-1.0'
    name = Column(Text, default=None)  # 'Creative Commons Zero'
    text = Column(Text, default=None)  # 'THE LICENSE TEXT'
    is_content = Column(Boolean, default=False)
    is_approved = Column(Boolean, default=False)
    requires_source = Column(Boolean, default=False)
    url = Column(Text, default=None)
    ctime = Column(DateTime, default=datetime.datetime.utcnow)

    alias_map = relationship(
        "LicenseAlias", back_populates="lic", cascade="all,delete,delete-orphan"
    )

    def __repr__(self) -> str:
        return f"License({self.license_id},{self.value})"

lvfs/licenses/routes.py
#!/usr/bin/python3
#
# Copyright 2020 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0-or-later

from typing import Any

from flask import Blueprint, request, url_for, redirect, flash, render_template, g
from flask_login import login_required
from sqlalchemy.exc import NoResultFound, IntegrityError

from lvfs import db

from lvfs.util import admin_login_required

from .models import License, LicenseAlias

bp_licenses = Blueprint("licenses", __name__, template_folder="templates")


@bp_licenses.route("/")
@login_required
@admin_login_required
def route_list() -> Any:
    licenses = db.session.query(License).order_by(License.value.asc()).all()
    return render_template("license-list.html", category="admin", licenses=licenses)


@bp_licenses.post("/create")
@login_required
@admin_login_required
def route_create() -> Any:
    # ensure has enough data
    try:
        value = request.form["value"]
    except KeyError:
        flash("No form data found!", "warning")
        return redirect(url_for("licenses.route_list"))
    if not value or value.find(" ") != -1:
        flash("Failed to add license: Value is not valid", "warning")
        return redirect(url_for("licenses.route_list"))

    # add license
    try:
        lic = License(value=request.form["value"])
        db.session.add(lic)
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("Failed to add license: The license already exists", "info")
        return redirect(url_for("licenses.route_list"))
    flash("Added license", "info")
    return redirect(url_for("licenses.route_show", license_id=lic.license_id))


@bp_licenses.post("/<int:license_id>/delete")
@login_required
@admin_login_required
def route_delete(license_id: int) -> Any:
    # get license
    try:
        db.session.query(License).filter(License.license_id == license_id).delete()
        db.session.commit()
    except IntegrityError:
        db.session.rollback()
        flash("License cannot be deleted", "info")
        return redirect(url_for("licenses.route_list"))
    flash("Deleted license", "info")
    return redirect(url_for("licenses.route_list"))


@bp_licenses.post("/<int:license_id>/modify")
@login_required
@admin_login_required
def route_modify(license_id: int) -> Any:
    # find license
    try:
        lic = (
            db.session.query(License)
            .filter(License.license_id == license_id)
            .with_for_update(of=License)
            .one()
        )
    except NoResultFound:
        flash("No license found", "info")
        return redirect(url_for("licenses.route_list"))

    # modify license
    lic.is_content = bool("is_content" in request.form)
    lic.is_approved = bool("is_approved" in request.form)
    lic.requires_source = bool("requires_source" in request.form)
    for key in ["name", "text", "url"]:
        if key in request.form:
            setattr(lic, key, request.form[key] or None)
    db.session.commit()

    # success
    flash("Modified license", "info")
    return redirect(url_for("licenses.route_show", license_id=license_id))


@bp_licenses.route("/<int:license_id>")
@login_required
@admin_login_required
def route_show(license_id: int) -> Any:
    # find license
    try:
        lic = db.session.query(License).filter(License.license_id == license_id).one()
    except NoResultFound:
        flash("No license found", "info")
        return redirect(url_for("licenses.route_list"))

    # show details
    return render_template("license-details.html", category="admin", lic=lic)


@bp_licenses.route("/<int:license_id>/alias/list")
@login_required
@admin_login_required
def route_alias_list(license_id: int) -> Any:

    try:
        lic = db.session.query(License).filter(License.license_id == license_id).one()
    except NoResultFound:
        flash("No license found", "info")
        return redirect(url_for("licenses.route_list"))
    return render_template(
        "license-alias-list.html",
        category="admin",
        lic=lic,
    )


@bp_licenses.post("/<int:license_id>/alias/create")
@login_required
@admin_login_required
def route_alias_create(license_id: int) -> Any:
    """Add a license alias"""
    try:
        value = request.form["value"]
        if value.find(" ") != -1:
            flash("Invalid alias value", "warning")
            return redirect(url_for("licenses.route_alias_list", license_id=license_id))
        lic = (
            db.session.query(License)
            .filter(License.license_id == license_id)
            .with_for_update(of=License)
            .one()
        )
        alias = LicenseAlias(value=value, user=g.user)
        lic.alias_map.append(alias)
        db.session.commit()
    except KeyError:
        flash("No form value", "warning")
        return redirect(url_for("licenses.route_alias_list", license_id=license_id))
    except NoResultFound:
        flash("Failed to get license details", "warning")
        return redirect(url_for("licenses.route_alias_list", license_id=license_id))
    except IntegrityError:
        db.session.rollback()
        flash("Failed to add license alias: already exists", "info")
        return redirect(url_for("licenses.route_alias_list", license_id=license_id))
    flash("Added alias value", "info")
    return redirect(
        url_for(
            "licenses.route_alias_list",
            license_id=license_id,
        )
    )


@bp_licenses.post("/<int:license_id>/alias/<int:license_alias_id>/delete")
@login_required
@admin_login_required
def route_alias_delete(license_id: int, license_alias_id: int) -> Any:
    """Delete a license alias"""
    try:
        lic_alias = (
            db.session.query(LicenseAlias)
            .filter(LicenseAlias.license_alias_id == license_alias_id)
            .join(License)
            .filter(License.license_id == license_id)
            .with_for_update(of=License)
            .one()
        )
        db.session.delete(lic_alias)
        db.session.commit()
    except NoResultFound:
        flash("Failed to get license", "warning")
        return redirect(url_for("licenses.route_list"))
    except IntegrityError:
        db.session.rollback()
        flash("Failed to remove license alias", "info")
        return redirect(url_for("licenses.route_list"))
    flash("Deleted alias value", "info")
    return redirect(
        url_for("licenses.route_alias_list", license_id=lic_alias.license_id)
    )

lvfs/licenses/templates/license-alias-list.html
{% extends "default.html" %}
{% block title %}License Alias Values{% endblock %}

{% block nav %}{% include 'license-nav.html' %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">License Alias Values for <code>{{lic.value}}</code></h2>
{% if lic.alias_values|length == 0 %}
    <p class="text-muted">No values have been added.</p>
{% endif %}
<table class="table card-text">
{% if lic.alias_values|length %}
  <tr class="row table-borderless">
    <th class="col col-sm-4">Value</th>
    <th class="col col-sm-6">Added by</th>
    <th class="col col-sm-2">&nbsp;</th>
  </tr>
{% endif %}
{% for lic_alias in lic.alias_map %}
  <tr class="row">
    <td class="col col-sm-4"><code>{{lic_alias.value}}</code></td>
    <td class="col col-sm-6">{{lic_alias.user.username}} {{format_humanize_naturaltime(lic_alias.ctime)}}</td>
    <td class="col col-sm-2">
      <form action="{{url_for('licenses.route_alias_delete', license_id=lic_alias.license_id, license_alias_id=lic_alias.license_alias_id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
        <button class="btn btn-block btn-warning">Delete</button>
      </form>
    </td>
  </tr>
{% endfor %}
<form method="post" action="{{url_for('licenses.route_alias_create', license_id=lic.license_id)}}">
<input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <tr class="row table-borderless">
    <td class="col col-sm-10">
      <input type="text" class="form-control" name="value" value="" placeholder="GPLv2+..." required>
    </td>
    <td class="col col-sm-2"><input type="submit" class="btn-block btn btn-primary" value="Add"></td>
  </tr>
</form>
</table>
  </div>
</div>

{% endblock %}

lvfs/licenses/templates/license-details.html
{% extends "default.html" %}
{% block title %}License Details{% endblock %}

{% block nav %}{% include 'license-nav.html' %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">License Details</h2>
<form method="post" action="{{url_for('licenses.route_modify', license_id=lic.license_id)}}">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <div class="form-group">
    <label for="value">Value:</label>
    <input type="text" class="form-control" id="value" name="value" value="{{lic.value}}" required />
  </div>
  <div class="form-group">
    <label for="name">Name:</label>
    <input type="text" class="form-control" id="name" name="name" value="{{lic.name if lic.name}}" required />
  </div>
  <div class="form-group">
    <label for="text">Text:</label>
    <textarea class="form-control" name="text" id="text" cols="90" rows="15">{{lic.text if lic.text}}</textarea>
  </div>
  <div class="form-group">
    <label for="text">URL:</label>
    <input type="text" class="form-control" id="url" name="url" value="{{lic.url if lic.url}}" />
  </div>
  <div class="form-group">
    <label for="is_content">
      <input class="checkbox" type="checkbox" id="is_content" name="is_content" value="1" {{'checked' if lic.is_content}} //>
      Is valid for metadata, e.g. a content license
    </label>
  </div>
  <div class="form-group">
    <label for="is_approved">
      <input class="checkbox" type="checkbox" id="is_approved" name="is_approved" value="1" {{'checked' if lic.is_approved}} //>
      Is approved by an entity like the FSF
    </label>
  </div>
  <div class="form-group">
    <label for="requires_source">
      <input class="checkbox" type="checkbox" id="requires_source" name="requires_source" value="1" {{'checked' if lic.requires_source}} //>
      Requires Source URL for binary firmware
    </label>
  </div>
  <input type="submit" class="card-link btn btn-primary" value="Save">
  <button type="button" class="card-link btn btn-danger" data-toggle="modal" data-target="#deleteModal">Delete</button>
</form>
  </div>
</div>

<!-- modal dialog -->
<div class="modal" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="deleteModalLabel">Really Delete License?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Once deleted, licenses can not be recovered.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <form action="{{url_for('licenses.route_delete', license_id=lic.license_id)}}" method="POST">
          <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
          <button class="btn btn-danger">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

lvfs/licenses/templates/license-list.html
{% extends "default.html" %}
{% block title %}Update Licenses{% endblock %}

{% block content %}

{% if licenses|length == 0 %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Licenses</h2>
    <p class="card-text">
      No licenses have been created.
    </p>
  </div>
</div>

{% else %}

{% for lic in licenses %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">
      {{lic.name}}
      <code class="float-right">{{lic.value}}</code>
    </h2>
    <a class="card-link btn btn-info"
      href="{{url_for('licenses.route_show', license_id=lic.license_id)}}"
      role="button">Details &raquo;</a>
  </div>
</div>
{% endfor %}

{% endif %}

<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">Create a new license</h2>
    <form method="post" action="{{url_for('licenses.route_create')}}" class="form">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <div class="form-group card-text">
        <label for="value">Value name, e.g. <code>CC0-1.0</code></label>
        <input class="form-control" type="text" id="value" name="value" placeholder="Value" required />
      </div>
      <input class="card-link btn btn-primary" type="submit" value="Add"/>
    </form>
  </div>
</div>

{% endblock %}

lvfs/licenses/templates/license-nav.html
<nav class="row">
  <div class="col col-sm-1 btn-group mb-3">
    <a class="btn btn-falcon-default mr-sm-3"
      href="{{url_for('licenses.route_list')}}">
      <img class="fa" src="{{url_for('cdn', filename='img/arrow-left-solid.svg')}}" width="16px" height="16px" />
    </a>
  </div>
  <div class="col col-sm-10 text-center mb-3">
    <div class="btn-group" role="group">
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'licenses.route_show' else 'default'}}"
        href="{{url_for('licenses.route_show', license_id=lic.license_id)}}">Details</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'licenses.route_alias_list' else 'default'}}"
        href="{{url_for('licenses.route_alias_list', license_id=lic.license_id)}}">Alias Values</a>
    </div>
  </div>
</nav>